In [1]:
import os
import json
import pprint
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
import inflection as inf
from collections import defaultdict
import random as random

In [81]:
#######################################################################################
############################# CHANGE FILENAMES HERE ###################################
#######################################################################################
filenames = os.listdir("../annotations/splits")
annotation_dir = "../annotations/splits"
determiners = ["a", "an", "all", "any", "every", "my", "your", "this", "that", "these", "those", "some", "many", "few", "both", "neither", "little", "much", "either", "our", "no", "several", "half", "each", "the"]
# filenames = ["annotations_val.json", "annotations_train.json", "annotations_test.json"]
# filenames = ["annotations_val.json"]
# filenames = ["train_001.json", "train_005.json", "train_010.json", "train_025.json", "train_050.json"]

save_dir = "../annotations/tfrecords/neurosym"


In [82]:
temp = json.load(open("../annotations/annotations_val.json", 'r'))
categories = temp["categories"]
n_categories = len(categories)

In [83]:
def image_feature(value):
    """Returns a bytes_list from a string / byte."""
    return tf.train.Feature(
        bytes_list=tf.train.BytesList(value=[tf.io.encode_png(value).numpy()])
    )

def bytes_feature(value):
    """Returns a bytes_list from a string / byte."""
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value.encode()]))

def float_feature(value):
    """Returns a float_list from a float / double."""
    return tf.train.Feature(float_list=tf.train.FloatList(value=[value]))

def int64_feature(value):
    """Returns an int64_list from a bool / enum / int / uint."""
    return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))

def int64_feature_list(value):
    """Returns a list of int_list from a int."""
    return tf.train.Feature(int64_list=tf.train.Int64List(value=value))

def float_feature_list(value):
    """Returns a list of float_list from a float / double."""
    return tf.train.Feature(float_list=tf.train.FloatList(value=value))

def object_features_list(objects): 
    feature_list = []
    for obj in objects:
        feature_list.append(int64_feature(obj["id"]))
    return tf.train.FeatureList(feature=feature_list)
    

def create_example(image_id, sample):
    caption = sample["image"]["caption"]
    file_name = sample["image"]["file_name"]
    det = caption.split()[0]
    noun = " ".join(caption.split()[1:])
    determiners.index(det)
    noun_id = 0 
    
    noun = inf.singularize(noun)
    for cat in categories: 
        if cat["name"] == noun: 
            noun_id = cat["id"]

    det_one_hot = [0 for i in range(len(determiners))]
    det_one_hot[determiners.index(det)] = 1
    noun_one_hot = [0 for i in range(len(categories))]
    noun_one_hot[noun_id] = 1
    caption_one_hot = det_one_hot + noun_one_hot
    
    max_bboxes = 20 
    
    input_one_hot = []
    output_one_hot =[]

    inputs = sample["inputs"]
    outputs = sample["outputs"]
    
    for ann in outputs: 
        one_hot = [0 for i in range(n_categories)]
        one_hot[ann["category_id"]] = 1
        output_one_hot.append(ann["bbox"] + [1] + one_hot)

    for j in range(len(output_one_hot), max_bboxes): 
        one_hot = [0 for i in range(n_categories)]
        output_one_hot.append([0,0,0,0] + [0] + one_hot)
            
    for ann in inputs: 
        one_hot = [0 for i in range(n_categories)]
        one_hot[ann["category_id"]] = 1
        if "liqLevel" not in ann.keys():
            ann["liqLevel"] = -1
        input_one_hot.append(ann["bbox"] + [1] + one_hot + [ann["liqLevel"]])
        
    for j in range(len(input_one_hot), max_bboxes): 
        one_hot = [0 for i in range(n_categories)]
        input_one_hot.append([0,0,0,0] + [0] + one_hot)

    #randonly shuffle a list of indices from 1 to 10
    indices = list(range(len(input_one_hot)))
    random.shuffle(indices)

    #shuffle input_one_hot according to indices
    input_one_hot = [input_one_hot[i] for i in indices]
    output_one_hot = [output_one_hot[i] for i in indices]
        
    context = {
        # "image": image_feature(image),
        "file_name": bytes_feature(file_name),
        "image_id": int64_feature(image_id),
        "caption": bytes_feature(caption),
        "caption_one_hot": int64_feature_list(caption_one_hot),
        "areas": int64_feature_list([ann['area'] for ann in inputs]), 
        "category_ids": int64_feature_list([ann['category_id'] for ann in inputs]), 
        "output_category_ids": int64_feature_list([ann['category_id'] for ann in outputs]),        
        "output_areas": int64_feature_list([ann['area'] for ann in outputs]),
    }

    feature_list = {
        "input_bboxes": tf.train.FeatureList(feature=[tf.train.Feature(int64_list=tf.train.Int64List(value=ann['bbox'])) for ann in inputs]),
        "output_bboxes": tf.train.FeatureList(feature=[tf.train.Feature(int64_list=tf.train.Int64List(value=ann['bbox'])) for ann in outputs]), 
        "input_one_hot": tf.train.FeatureList(feature=[tf.train.Feature(int64_list=tf.train.Int64List(value=[int(v) for v in val])) for val in input_one_hot]),
        "output_one_hot": tf.train.FeatureList(feature=[tf.train.Feature(int64_list=tf.train.Int64List(value=[int(v) for v in val])) for val in output_one_hot]),
    }
     
    return tf.train.SequenceExample(context=tf.train.Features(feature=context), feature_lists=tf.train.FeatureLists(feature_list=feature_list))

def parse_tfrecord_fn(example, labeled=True):
    feature_description = {
        "file_name": tf.io.FixedLenFeature([], tf.string),
        #         "image": tf.io.FixedLenFeature([], tf.string),
        "image_id": tf.io.FixedLenFeature([], tf.int64),
        "caption": tf.io.VarLenFeature(tf.string),
        "caption_one_hot": tf.io.VarLenFeature(tf.int64),
        "areas": tf.io.VarLenFeature(tf.int64),
        "category_ids": tf.io.VarLenFeature(tf.int64),
        "output_category_ids": tf.io.VarLenFeature(tf.int64),
        "output_areas": tf.io.VarLenFeature(tf.int64)
    }

    sequence_features = {
        "input_bboxes": tf.io.VarLenFeature(tf.int64),
        "output_bboxes": tf.io.VarLenFeature(tf.int64),
        "input_one_hot": tf.io.VarLenFeature(tf.int64),
        "output_one_hot": tf.io.VarLenFeature(tf.int64)
    }
    context, sequence = tf.io.parse_single_sequence_example(example, context_features=feature_description,
                                                            sequence_features=sequence_features)

    example = {**context, **sequence}
    for key in example.keys():
        if type(example[key]) == tf.sparse.SparseTensor:
            if (example[key].dtype == "string"):
                example[key] = tf.sparse.to_dense(example[key], default_value='b')
            else:
                example[key] = tf.sparse.to_dense(example[key])

    prefix = "../DetermiNetProject/Assets/StreamingAssets/dataset/"
    # raw = tf.io.read_file(prefix + example["file_name"])
    # example["image"] = tf.io.decode_png(raw, channels=3)

    return example

In [84]:

for filename in filenames:
    annotation_filepath = os.path.join(annotation_dir, filename)
    dataset = json.load(open(annotation_filepath, 'r'))
    images = dataset["images"]
    input_annotations = dataset["input_oracle_annotations"]
    output_annotations = dataset["annotations"]
    n_samples = 4096
    n_tfrecords = len(images) // n_samples
    if len(images) % n_samples: 
        n_tfrecords += 1 
    
    split_dir = os.path.join(save_dir, filename.split(".")[0].split("_")[1])
    print(split_dir)
    if not os.path.exists(split_dir): 
        os.makedirs(split_dir)

    dataset_samples = defaultdict(lambda: defaultdict(list))

    for ann in input_annotations: 
        dataset_samples[ann["image_id"]]["inputs"].append(ann)
        
    for ann in output_annotations: 
        dataset_samples[ann["image_id"]]["outputs"].append(ann)

    for image in images: 
        dataset_samples[image["id"]]["image"] = image

    keys = list(dataset_samples.keys())
    for tfrec_num in range(n_tfrecords): 
        sample_keys = keys[tfrec_num*n_samples : (tfrec_num + 1) * n_samples]
        
        with tf.io.TFRecordWriter(
            split_dir + "/file_%.2i-%i.tfrec" % (tfrec_num, len(sample_keys))
        ) as writer:
            for key in sample_keys:
                dataset_sample = dataset_samples[key] 
                input_objects = dataset_samples[key]["input"]
                output_objects = dataset_samples[key]["output"]
                example = create_example(key, dataset_sample)
                writer.write(example.SerializeToString())

../annotations/tfrecords/neurosym\0point1
../annotations/tfrecords/neurosym\0point25
../annotations/tfrecords/neurosym\1
../annotations/tfrecords/neurosym\10
../annotations/tfrecords/neurosym\25
../annotations/tfrecords/neurosym\2point5
../annotations/tfrecords/neurosym\5
../annotations/tfrecords/neurosym\50


In [80]:
def map_to_inputs(example):
    # image = example["image"]
    caption = example["caption"]
    input_bbox = example["input_bboxes"]
    input_label = example["category_ids"]
    output_labels = example["output_category_ids"]
    input_one_hot = tf.cast(example["input_one_hot"], dtype=tf.float64)
    output_bboxes = example["output_bboxes"]
    output_one_hot = tf.cast(example["output_one_hot"], dtype=tf.float64)
    caption_one_hot = example["caption_one_hot"]
    print(input_one_hot)

    input_one_hot = tf.concat([input_one_hot[:, :4] / 256, input_one_hot[:, 4:]], axis=1)
    output_one_hot = tf.concat([output_one_hot[:, :4] / 256, output_one_hot[:, 4:]], axis=1)
    #     input_mask =
    output_mask = tf.stack(output_one_hot[:, 4])
    n_pad = 20 - tf.shape(output_labels)[0]
    output_labels_padded = tf.pad(output_labels, [[0, n_pad]], "CONSTANT")
    return (input_one_hot, caption_one_hot), (output_mask), output_one_hot

In [65]:
train_filenames = tf.io.gfile.glob(f"../annotations/old/*.tfrec")
print(train_filenames)
AUTOTUNE = tf.data.AUTOTUNE
BATCH_SIZE = 64

train_dataset = tf.data.TFRecordDataset(train_filenames, num_parallel_reads=AUTOTUNE)
train_dataset = train_dataset.map(parse_tfrecord_fn, num_parallel_calls=AUTOTUNE)
train_dataset = train_dataset.map(map_to_inputs, num_parallel_calls=AUTOTUNE)
train_dataset = train_dataset.shuffle(4 * BATCH_SIZE)
train_dataset = train_dataset.prefetch(buffer_size=AUTOTUNE)
train_dataset = train_dataset.batch(BATCH_SIZE)
example = next(iter(train_dataset))

['..\\annotations\\old\\file_00-104.tfrec']
Tensor("Cast:0", shape=(None, None), dtype=float64)


In [66]:
for i in example[1]: 
    print(i)

tf.Tensor([0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0.], shape=(20,), dtype=float64)
tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], shape=(20,), dtype=float64)
tf.Tensor([1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(20,), dtype=float64)
tf.Tensor([1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(20,), dtype=float64)
tf.Tensor([0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], shape=(20,), dtype=float64)
tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], shape=(20,), dtype=float64)
tf.Tensor([0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.], shape=(20,), dtype=float64)
tf.Tensor([1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0.], shape=(20,), dtype=float64)
tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0.], shape=(20,), dtype=float64)
tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], shape=(20,), dtype

In [41]:
print(example[0][0][0])

tf.Tensor(
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0. 

In [46]:
example[1][0]

<tf.Tensor: shape=(20,), dtype=float64, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0.])>